name: Doodstream Automation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari branch master
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js untuk menjalankan kode
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install axios sqlite3

      # Jalankan skrip
      - name: Run script
        run: node script.js

      # Simpan database hasil ke branch `database`
      - name: Push dood.db to database branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b database
          git add dood.db
          git commit -m "Add dood.db"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} database
    env:
      API_KEY: 350871o0uomobcm787efod
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
