name: Run Node.js Script and Upload Database

on:
  push:
    branches:
      - master

jobs:
  run-script:
    name: Execute Node.js Script
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Node.js Environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Run Node.js Script
      - name: Execute Script
        run: node api2db.js

      # Commit and Push Database File
      - name: Commit and Push dood.db to 'database' branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b database
          git add dood.db
          git commit -m "Add dood.db database"
          git push origin database
